import NavBar from './components/nav-bar';
import { cookies } from 'next/headers';
import './globals.css';

export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'Nextjs App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  const cookieStore = cookies();
  console.log(cookieStore)
  const userInfoString = cookieStore.get('userInfo')?.value || null;
  const userInfo = userInfoString ? JSON.parse(decodeURIComponent(userInfoString)) : null;
  
  return (
    <html>
      <body className="pt-16">
        <NavBar userInfo={userInfo}/>
          {children}
      </body>
    </html>
  );
}

