export const metadata = {
  title: 'Nextjs App',
  description: 'Generated by create next app',
}

export default function NewBlogLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
    </>
  )
}
